"""initial schema

Revision ID: 394a4055195b
Revises: 
Create Date: 2026-06-24 04:03:37.511260
"""
from alembic import op
import sqlalchemy as sa


revision = '394a4055195b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('delivery_channels', sa.String(length=256), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clip_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_acknowledged'), ['acknowledged'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_rule'), ['rule'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_ts'), ['ts'], unique=False)

    op.create_table('config_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_history_ts'), ['ts'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('person_count', sa.Integer(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('max_temp_c', sa.Float(), nullable=False),
    sa.Column('min_temp_c', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('detector_backend', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_events_ts_frame', ['ts', 'frame_index'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dwell_seconds', sa.Float(), nullable=False),
    sa.Column('peak_temp_c', sa.Float(), nullable=False),
    sa.Column('frames', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_track_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_ts_frame')
        batch_op.drop_index(batch_op.f('ix_events_ts'))

    op.drop_table('events')
    with op.batch_alter_table('config_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_history_ts'))

    op.drop_table('config_history')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_ts'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_rule'))
        batch_op.drop_index(batch_op.f('ix_alerts_key'))
        batch_op.drop_index(batch_op.f('ix_alerts_acknowledged'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
